import {mkdir,writeFile} from 'node:fs/promises';
const arrow='<svg class="arrow" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15M13 5l7 7-7 7"/></svg>';
const source='<p class="source">출처: 경력 포트폴리오 기획안 · 2026년 9월 정리<br>집계 기간 및 관리자 원본은 추가 확인 예정입니다.</p>';
const projects=[
{id:'crm',category:'CRM · 고객 여정',name:'CRM 운영 구조 재설계',summary:'발송량보다 고객 여정과 우선순위를 먼저 정리했습니다.',outcome:'ROAS 877% → 1,788%',foot:'매출 −72.2% 함께 확인',title:'저효율 발송을 줄이고,<br>전환의 질을 높이다.',intro:'캠페인의 발송 시간과 고객 세그먼트를 다시 정리해 비용 효율을 개선하고, 다음 확장을 위한 운영 기준을 만들었습니다.',role:'고객 여정 설계 · 발송 운영 · 소재 제작 · 분석',scope:'SnapPush · Datarize · Figma',sections:[
['problem','발송이 겹치고, 고객 여정에는 공백이 있었습니다.','<p>캠페인별 발송 시간이 겹쳤지만 세그먼트 사이의 우선순위는 명확하지 않았습니다. 신규 고객과 장기 미방문 고객을 관리하는 흐름에도 공백이 있었습니다.</p><p>UTM 유입 분석과 플랫폼 관리자 성과의 귀속 기준까지 달라, 어떤 실행이 효과적이었는지 일관되게 판단하기 어려웠습니다.</p>'],
['decision','발송 대상을 나누고, 먼저 보낼 메시지를 정했습니다.','<p>고객을 신규·고관심·기존 구매·장기 미방문으로 나누고 발송 시간대와 캠페인 우선순위를 재정리했습니다. 중복 발송을 줄이는 동시에 관리가 비어 있던 고객군을 여정 안에 포함했습니다.</p>'+flow([['신규 고객','첫 방문 이후의 관계 형성'],['고관심 고객','관심 상품과 혜택 연결'],['기존 구매 고객','구매 이후의 다음 제안'],['장기 미방문','다시 방문할 이유 설계']])+'<p class="flow-caption">기획안의 고객 구분을 재구성한 개념도입니다. 실제 관리자 화면이 아닙니다.</p><p>SnapPush와 Datarize 운영 데이터를 비교하고 UTM 규칙과 성과 기록 방식을 정리했습니다. 대표 CRM은 프로모션 랜딩의 혜택과 시각 구조를 이어받도록 기획하고 Figma 소재까지 제작했습니다.</p>'],
['results','효율은 좋아졌고, 매출 규모는 줄었습니다.',table(['지표','이전','이후 / 변화'],[['광고비 지수','100','13.7 (−86.3%)'],['ROAS','877%','<strong>1,788%</strong>'],['CVR','3.3%','<strong>4.7%</strong>'],['매출 지수','100','27.8 (−72.2%)']])+source+'<p class="note">이 사례의 결과는 매출 성장이 아닙니다. 저효율 집행을 줄여 비용 효율과 전환 품질을 높였지만 매출 규모도 감소했습니다. 다음 과제는 개선된 기준을 유지하면서 발송과 매출을 다시 확장하는 것입니다.</p>'],
['limits','같은 기준으로 비교할 수 있는 증빙을 남깁니다.','<p>ROAS는 매출 ÷ 광고비 × 100으로 읽습니다. CVR은 원본의 전환 분모와 비교 기간 확인이 필요합니다. 관리자 주문과 UTM 귀속 주문은 별도 지표로 관리합니다.</p><p>비교 기간이 보이는 관리자 화면, 발송 캘린더 전후, 세그먼트 정의와 대표 소재를 추가하면 개선 과정과 성과를 함께 검증할 수 있습니다.</p>']]},
{id:'promotion',category:'프로모션 · 운영 설계',name:'프로모션 PM에서 운영 시스템으로',summary:'혜택·쿠폰·랜딩·QA를 연결하고 반복 오류를 구조적으로 다뤘습니다.',outcome:'두 브랜드의 운영 흐름 통합',foot:'프로덕션 운영 중',title:'출시를 직접 운영하며,<br>반복 오류의 구조를 바꾸다.',intro:'혜택과 가격 설계에서 Cafe24 실행, CRM, QA까지 연결한 경험을 Promotion Ops System으로 확장했습니다.',role:'프로모션 PM · 시스템 단독 기획·설계·개발',scope:'WBL · VIVOIR · Cafe24',sections:[
['problem','하나의 변경을 여러 곳에 반영해야 했습니다.','<p>프로모션의 상품·혜택·기간을 바꿀 때마다 분산된 설정을 다시 맞춰야 했습니다. 쿠폰, 랜딩, CRM, 물류와 성과 집계가 서로 다른 흐름으로 움직이면 출시 전후 오류로 이어졌습니다.</p>'+table(['기존 문제','문서에 기록된 사례'],[['설정 분산','바뀐 값을 6곳에 반복 반영'],['쿠폰 오생성','라이브몰 쿠폰 12장 오생성'],['사은품 누락','미출고 97건'],['성과 중복','동일 매출의 3중 집계']])+'<p class="source">시스템 구축의 배경이 된 문제 사례입니다. 도입 후 개선 실적을 뜻하지 않습니다.</p>'],
['decision','고객이 이해할 혜택부터, 실제 출시 조건까지.','<p>WBL Summer Silver Holiday와 추석감사제에서는 다단 쿠폰, 사은품, 랜딩, CRM 사이의 정합성을 관리했습니다. VIVOIR 추석 선물전에서는 제품을 명절의 사용 상황에 맞춰 재분류하고, 세트 구성과 가격·예상 마진을 함께 검토했습니다.</p>'+flow([['사업 조건','재고 · 원가율 · 채널 제약'],['혜택 설계','세트 · 가격 · 쿠폰 · 사은품'],['실행 연결','Cafe24 · 랜딩 · CRM'],['출시 검증','기간 · 옵션가 · 재고 · 물류']])+'<p class="flow-caption">프로모션 실행 범위를 정리한 개념도입니다.</p><p>페이지 카피에서 쿠폰과 금액별 사은품의 오해를 줄이고, 콘텐츠 블록과 JSON을 실제 페이지에 연결했습니다. 오픈 전에는 URL·중복·기간·옵션가·재고·물류를 확인했습니다.</p>'],
['results','기획부터 성과까지 같은 정보로 이어지게 했습니다.',table(['업무','시스템에서 연결한 흐름'],[['회차 기획','결정문과 선례를 바탕으로 기획안 생성'],['쿠폰 실행','자동 생성 후 재조회 검증'],['페이지 제작','페이지 JSON 내보내기와 에디터 불러오기'],['사전 QA','마진과 쿠폰 조건 검사'],['성과 분석','쿠폰명 태그로 캠페인 성과 그룹화']])+'<p>WBL과 VIVOIR 두 브랜드를 대상으로 20일 동안 22개 화면과 82개 API 경로를 구축했습니다. 기획안 기준 Railway 프로덕션에서 운영 중입니다.</p>'+source+'<p class="note">모든 이상을 작업 중단 조건으로 두면 예외가 많은 실무를 막을 수 있습니다. 되돌리기 어려운 외부 쓰기는 차단하고, 나머지는 기본값·자동 보정·경고로 처리하는 기준을 설계했습니다. 검증하지 못한 항목은 미검증 상태로 남깁니다.</p>'],
['limits','도입과 효과 측정은 구분합니다.','<p>현재 확인된 서술은 프로덕션 운영 상태입니다. 회차 세팅 시간, 오픈 후 수정 건수, 쿠폰 오설정 건수의 개선 폭은 실측 후 추가할 항목입니다.</p><p>사은품 배선, 겹치는 상품 대체 추천, 레거시 콘솔 퇴역은 다음 단계입니다. 완료 성과로 표현하지 않습니다.</p>']]},
{id:'workbench',category:'PPL · 업무 도구',name:'PPL Workbench 구축과 도입',summary:'크리에이터 검토부터 성과 회고까지, 흩어진 정보를 연결했습니다.',outcome:'마케팅팀 공식 도구 채택',foot:'현업 흐름을 제품으로',title:'흩어진 PPL 업무를<br>팀이 쓰는 하나의 흐름으로.',intro:'크리에이터 검토, 제안, 실행, 추적과 회고를 같은 정보 구조로 연결하는 업무 도구를 만들었습니다.',role:'업무 정의 · 웹앱 구현 · 운영 피드백 반영',scope:'Google Apps Script · Claude Code',sections:[
['problem','진행 상태보다 정보를 찾는 일이 먼저였습니다.','<p>크리에이터 검토, 단가, 일정, 메일, UTM, 랜딩과 성과 정보가 여러 시트와 대화방에 흩어져 있었습니다. 제안부터 발행과 ROAS 회고까지 같은 정보를 반복 입력했고, 누락 여부를 한눈에 보기 어려웠습니다.</p>'],
['decision','기능 목록보다 실무의 판단 순서를 먼저 정했습니다.',flow([['검토 · 제안','채널 적합도 · 조건 · 일정'],['실행','가이드 · 계약 · 배송 · QA'],['추적','랜딩 · 쿠폰 · UTM'],['회고','브랜드별 성과와 히스토리']])+'<p class="flow-caption">기획안에 제시된 업무 흐름을 재구성한 개념도입니다.</p><p>현업의 판단 단계와 필수 필드를 직접 정의했습니다. 크리에이터 비교와 검토 기록, 메일 템플릿과 제안 상태, 실행 체크리스트를 같은 흐름 안에 배치했습니다.</p><p>Claude Code와 Google Apps Script를 활용해 웹앱으로 구현하고 운영 피드백을 반영했습니다. 기능 수를 늘리기보다 실제 비브아 캠페인 한 사이클을 끝까지 운영할 수 있는 흐름을 우선했습니다.</p>'],
['results','마케팅팀의 공식 업무 도구로 채택됐습니다.','<p>크리에이터 검토부터 성과 회고까지 같은 정보 구조를 재사용할 수 있게 됐습니다. 기획안은 마케팅팀 공식 업무 도구 채택을 결과로 기록하고 있습니다.</p>'+source+'<p class="note">이 사례의 핵심 결과는 도구의 실제 채택입니다. 시간 절감률이나 매출 증가율은 측정 자료가 없어 제시하지 않습니다.</p>'],
['limits','완료 기능과 다음 단계를 나눕니다.','<p>모두싸인 API 계약 연동은 미완료 로드맵입니다. 실제 운영 화면과 도입 확인 자료를 보완하고, 반복 입력 감소와 누락 방지 효과는 별도로 측정할 계획입니다.</p>']]},
{id:'campaigns',category:'캠페인 · 성과 분석',name:'성과형 캠페인 실행',summary:'소재 기획과 발송 운영, 광고 지원의 결과를 집계 기준에 맞춰 읽었습니다.',outcome:'대표 CRM ROAS 597%',foot:'단일 발송 사례',title:'실행의 결과를,<br>숫자의 기준까지 읽다.',intro:'CRM 소재와 발송 운영은 직접 수행하고, GFA 스마트스토어는 운영 지원과 성과 분석 범위로 구분했습니다.',role:'CRM 기획·제작·발송 · GFA 운영 지원·분석',scope:'CRM · Figma · GFA · 스마트스토어',sections:[
['problem','프로모션의 혜택이 메시지에서도 이어져야 합니다.','<p>메시지의 시각 구조와 혜택이 랜딩의 내용과 이어져야 클릭 이후에도 고객이 같은 제안을 이해할 수 있습니다. 럭키세븐투위크 CRM에서는 소재 기획과 Figma 제작, 발송 운영을 담당했습니다.</p>'],
['decision','대표 발송과 최근 운영 규모를 나누어 봅니다.',table(['럭키세븐투위크 CRM','결과'],[['ROAS','597%'],['CVR','4.2%'],['CTR','3.4%']])+table(['최근 CRM 운영','결과'],[['발송 / 클릭','7,929건 / 359건'],['CTR','4.5%'],['관리자 주문','31건'],['클릭 후 주문전환','8.6%'],['비용','158,280원']])+source+'<p class="note">최근 CRM의 CTR은 359 ÷ 7,929 ≈ 4.5%, 클릭 후 주문전환은 31 ÷ 359 ≈ 8.6%입니다. 플랫폼 관리자 주문을 UTM 분석 주문 또는 다른 캠페인 결과와 합산하지 않습니다.</p>'],
['results','광고 성과와 담당 범위를 함께 보여줍니다.',table(['GFA 스마트스토어','결과'],[['노출','274,687회'],['클릭','2,247회'],['광고비','813,869원'],['구매매출','1,571,000원'],['ROAS','193.03%']])+'<p>담당 범위는 운영 지원, 랜딩 연결과 성과 분석입니다. ROAS는 구매매출 ÷ 광고비 × 100으로 계산했습니다.</p>'+source],
['limits','운영 결과를 전환 성과로 확대 해석하지 않습니다.','<p>PPL 크리에이터 운영에서는 무상 협찬 13건과 확인된 6개 콘텐츠 조회수 48,922회를 기록했습니다. 발굴부터 배송·발행 관리까지의 운영 결과이며 매출이나 전체 콘텐츠 조회수를 뜻하지 않습니다.</p><p>각 캠페인의 기간, 관리자 원본, 광고의 귀속 기준과 발행 링크를 추가해 성과의 맥락을 보완할 수 있습니다.</p>']]}
];
function flow(items){return '<div class="flow">'+items.map(([a,b])=>`<div><b>${a}</b><span>${b}</span></div>`).join('')+'</div>';}
function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>i?`<td>${x}</td>`:`<th scope="row">${x}</th>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function shell(title,body,depth=''){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="남귀현의 경력 포트폴리오. CRM과 프로모션 실행에서 반복 가능한 운영 시스템까지."><meta name="theme-color" content="#183b50"><title>${title} | 남귀현 포트폴리오</title><link rel="stylesheet" href="${depth}assets/style.css"><script defer src="${depth}assets/app.js"></script></head><body><a class="skip" href="#main">본문으로 건너뛰기</a><div class="wrap"><header class="header"><a class="brand" href="${depth}index.html">남귀현<span>경력 포트폴리오</span></a><nav class="nav" aria-label="주 메뉴"><a href="${depth}index.html#projects">프로젝트</a><a href="${depth}index.html#about">소개</a></nav></header>${body}<footer class="footer"><span>남귀현 · CRM과 프로모션, 그리고 운영 시스템</span><span>2026년 9월 기준 · <button class="print" data-print>이 페이지 인쇄</button></span><a href="#main">맨 위로</a></footer></div></body></html>`;}
const home=`<main id="main"><section class="hero intro-fade"><div class="hero-top"><div class="switch" role="group" aria-label="포트폴리오 관점"><button data-view="marketing" aria-pressed="true">CRM·마케팅</button><button data-view="ops" aria-pressed="false">운영 시스템</button></div></div><h1 data-hero>고객의 다음 행동을 설계하고,<br><em>반복되는 일을 시스템으로.</em></h1><div class="hero-bottom"><p>안녕하세요, 이커머스 마케터 남귀현입니다.<br>고객 여정부터 프로모션 실행, 성과 분석까지 연결합니다.</p><a class="text-link" href="#projects">프로젝트 살펴보기 ${arrow}</a></div></section><section class="result-panel" aria-labelledby="result-title"><div><h2 id="result-title">발송을 늘리기 전에,<br>운영 구조를 바꿨습니다.</h2><p>CRM 운영 재설계의 전후 변화<br>비용 효율과 매출 규모를 함께 봅니다.</p></div><div><div class="chart-head"><span>핵심 지표</span><span>이전</span><span>재설계 이후</span></div><div class="chart-row"><span>ROAS</span><strong class="before">877%</strong><strong class="after">1,788%</strong></div><div class="chart-row"><span>CVR</span><strong class="before">3.3%</strong><strong class="after">4.7%</strong></div><div class="change-summary"><span>광고비 <b>−86.3%</b></span><span>매출 <b>−72.2%</b></span></div></div></section>${source}<section class="section" id="projects"><div class="section-head"><h2>실행에서 구조로</h2><p>문제와 판단, 실행과 결과를 담은 네 가지 사례</p></div><div class="project-list">${projects.map(p=>`<a class="project" data-project="${p.id}" data-case-link href="projects/${p.id}.html"><span class="category">${p.category}</span><div class="summary"><h3>${p.name}</h3><p>${p.summary}</p></div><div class="outcome">${p.outcome}<small>${p.foot}</small></div>${arrow}</a>`).join('')}</div></section><section class="section about-grid" id="about"><h2>한 번의 실행이<br>다음의 기준이 되도록.</h2><div class="about-copy"><p>캠페인을 실행하면서 발견한 문제를 기록하고,<br>다음 운영에서 다시 쓸 수 있는 규칙으로 정리합니다.</p><div class="roles"><div><h3>고객 여정과 CRM</h3><p>세그먼트와 발송 우선순위, 소재 제작부터 성과 기록까지 연결합니다.</p></div><div><h3>프로모션 PM</h3><p>상품과 혜택, Cafe24와 랜딩, CRM과 QA를 하나의 출시 흐름으로 다룹니다.</p></div><div><h3>업무 시스템</h3><p>실무의 판단과 필수 조건을 정의하고, 반복 입력과 검증을 도구로 옮깁니다.</p></div><div><h3>성과를 읽는 방식</h3><p>개인 기여와 팀 결과, 달성값과 목표, 서로 다른 귀속 기준을 구분합니다.</p></div></div></div></section></main>`;
await mkdir('site/projects',{recursive:true});await writeFile('site/index.html',shell('CRM과 프로모션을 운영 시스템으로',home));
for(let i=0;i<projects.length;i++){const p=projects[i];const next=projects[(i+1)%projects.length];const body=`<main id="main"><div class="breadcrumb"><a href="../index.html#projects">프로젝트</a> / ${p.name}</div><header class="case-hero"><h1>${p.title}</h1><p class="lede">${p.intro}</p><dl class="meta"><div><dt>담당 범위</dt><dd>${p.role}</dd></div><div><dt>운영 환경</dt><dd>${p.scope}</dd></div><div><dt>자료 기준</dt><dd>2026년 9월 기획안</dd></div></dl></header><div class="case-layout"><nav class="toc" aria-label="사례 목차"><a href="#problem">배경과 문제</a><a href="#decision">판단과 실행</a><a href="#results">결과와 해석</a><a href="#limits">한계와 다음 단계</a></nav><article>${p.sections.map(([id,title,html])=>`<section class="case-section" id="${id}"><h2>${title}</h2>${html}</section>`).join('')}</article></div><nav class="case-bottom" aria-label="다른 프로젝트"><a class="text-link" href="../index.html#projects">프로젝트 목록</a><a class="text-link" href="${next.id}.html">${next.name} ${arrow}</a></nav></main>`;await writeFile(`site/projects/${p.id}.html`,shell(p.name,body,'../'));}
await writeFile('site/.nojekyll','');
await writeFile('site/404.html',shell('페이지를 찾을 수 없습니다','<main id="main" class="hero"><h1>페이지를 찾을 수 없습니다.</h1><p class="lede">주소를 확인하거나 포트폴리오 홈으로 돌아가 주세요.</p><a class="text-link" href="./index.html">포트폴리오 홈</a></main>'));
const {readFile}=await import('node:fs/promises');
await writeFile('site/404.html',(await readFile('site/404.html','utf8')).replace('<head>','<head><base href="https://namgh98-star.github.io/nam-gwihyeon-portfolio/">'));
console.log('홈, 프로젝트 4개, 404 페이지 생성 완료');
