import {mkdir,writeFile} from 'node:fs/promises';
const arrow='<svg class="arrow" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15M13 5l7 7-7 7"/></svg>';
const source='<p class="source">출처: 경력 포트폴리오 기획안 · 2026년 9월 정리<br>집계 기간 및 관리자 원본은 추가 확인 예정입니다.</p>';
const dashboardSource='<p class="source">출처: CRM 성과 대시보드 · 2026년 9월 확인<br>플랫폼별 귀속 기준과 관리자 원본은 추가 확인 예정입니다.</p>';
const meetingSource='<p class="source">근거: [wbL X 스냅푸시] 260820 미팅 자료<br>외부 파트너의 현황 분석과 제안이며 개인 단독 성과를 뜻하지 않습니다.</p>';
const projects=[
{id:'crm',category:'CRM · Marketing Ops',name:'CRM 성과관리 체계화',summary:'흩어진 발송·클릭·주문·매출을 같은 기준으로 연결했습니다.',outcome:'31개 캠페인 · 19.3만 건',foot:'4개 플랫폼 성과 통합',title:'흩어진 CRM 데이터를,<br>하나의 판단 기준으로.',intro:'플랫폼마다 달랐던 발송·클릭·주문·매출의 기준을 구분하고, 고객 유입과 이탈을 함께 읽을 수 있는 운영 구조로 정리했습니다.',role:'CRM 운영 · 성과 정리 · 기준 설계 · 분석',scope:'Cafe24 · Datarize · SnapPush · App Push',basis:'2026년 8–9월 CRM 자료',sections:[
['problem','신규 고객은 늘었지만, 장기 미방문 고객도 함께 늘었습니다.','<p>신규 회원은 2026년 4월 3,317명을 저점으로 5월 +25.4%, 6월 +24.8%, 7월 +8.2% 증가해 7월 5,616명을 기록했습니다. 반면 마지막 방문 후 181일 이상 지난 고객도 1월 463,224명에서 8월 522,057명으로 늘었습니다.</p><p>유입 증가만 보면 성장처럼 보이지만, 신규 고객의 전환 의존도와 장기 미방문 고객의 확대를 함께 보면 첫 구매 전환과 재활성화를 별도 과제로 관리해야 했습니다.</p>'+meetingSource+'<p>동시에 CRM 성과가 Cafe24, Datarize, SnapPush와 앱푸시에 나뉘어 있어 어떤 캠페인이 실제 주문과 매출에 기여했는지 같은 기준으로 비교하기 어려웠습니다.</p>'],
['decision','고객 상태와 성과 기준을 함께 구조화했습니다.','<p>신규·고관심·멤버십·기존 구매·장기 미방문으로 고객 상태를 나누고, 각 여정에서 필요한 메시지와 관리 목적을 구분했습니다. 여기에 캠페인명, 채널, 오디언스, 소재와 UTM을 연결해 발송·클릭·주문·매출을 같은 흐름에서 비교하도록 정리했습니다.</p>'+flow([['유입','신규 가입 · 첫 구매'],['관심','상품 탐색 · 장바구니'],['관계','멤버십 · 재구매'],['재활성화','장기 미방문 · 이탈 방지']])+'<p class="flow-caption">고객 생애주기와 CRM 관리 목적을 재구성한 개념도입니다.</p><p>플랫폼 관리자 주문과 UTM 귀속 주문은 별도 지표로 유지하고, 귀속 기준이 확인되지 않은 값은 합산하지 않았습니다. 발송지표 미반영 57건, 검증 대기 UTM 22건, 카피·오디언스 미매핑 86개와 성과 측정 불가 15개도 보완 과제로 분리했습니다.</p>'],
['results','운영 규모와 전환 성과를 한 흐름에서 읽었습니다.',table(['성과관리 범위','확인 값'],[['연결한 캠페인','31개'],['발송 규모','약 19.3만 건'],['추적 전환매출','1,186만 원'],['추적 주문','149건']])+dashboardSource+'<p class="note">전환매출 1,186만 원과 주문 149건은 담당 기간 대시보드에서 추적한 운영 결과입니다. 회사 전체 성과나 개인 단독 기여로 확대하지 않으며, 플랫폼별 귀속 기준을 함께 확인합니다.</p>'],
['limits','효율이 좋아져도, 규모가 줄면 성장이라고 말하지 않습니다.','<p>외부 파트너와의 성과 리뷰에서도 ROAS와 전환율은 개선됐지만 발송량과 매출 규모가 함께 감소한 흐름이 확인됐습니다. 효율과 규모를 분리해 읽고, 좋은 비율 하나를 전체 성장으로 확대 해석하지 않는 것이 이 사례에서 남긴 기준입니다.</p>'+meetingSource+'<p>다음 단계는 UTM과 소재 분류를 발송 전에 검증하고, 고객 1천 명당 매출과 반복 구매를 비교하며 신규 전환과 장기 미방문 재활성화를 함께 관리하는 것입니다.</p>']]},
{id:'promotion',category:'프로모션 · 운영 설계',name:'프로모션 PM에서 운영 시스템으로',summary:'혜택·쿠폰·랜딩·QA를 연결하고 반복 오류를 구조적으로 다뤘습니다.',outcome:'두 브랜드의 운영 흐름 통합',foot:'프로덕션 운영 중',title:'출시를 직접 운영하며,<br>반복 오류의 구조를 바꾸다.',intro:'혜택과 가격 설계에서 Cafe24 실행, CRM, QA까지 연결한 경험을 Promotion Ops System으로 확장했습니다.',role:'프로모션 PM · 시스템 단독 기획·설계·개발',scope:'WBL · VIVOIR · Cafe24',sections:[
['problem','하나의 변경을 여러 곳에 반영해야 했습니다.','<p>프로모션의 상품·혜택·기간을 바꿀 때마다 분산된 설정을 다시 맞춰야 했습니다. 쿠폰, 랜딩, CRM, 물류와 성과 집계가 서로 다른 흐름으로 움직이면 출시 전후 오류로 이어졌습니다.</p>'+table(['기존 문제','문서에 기록된 사례'],[['설정 분산','바뀐 값을 6곳에 반복 반영'],['쿠폰 오생성','라이브몰 쿠폰 12장 오생성'],['사은품 누락','미출고 97건'],['성과 중복','동일 매출의 3중 집계']])+'<p class="source">시스템 구축의 배경이 된 문제 사례입니다. 도입 후 개선 실적을 뜻하지 않습니다.</p>'],
['decision','고객이 이해할 혜택부터, 실제 출시 조건까지.','<p>WBL Summer Silver Holiday와 추석감사제에서는 다단 쿠폰, 사은품, 랜딩, CRM 사이의 정합성을 관리했습니다. VIVOIR 추석 선물전에서는 제품을 명절의 사용 상황에 맞춰 재분류하고, 세트 구성과 가격·예상 마진을 함께 검토했습니다.</p>'+flow([['사업 조건','재고 · 원가율 · 채널 제약'],['혜택 설계','세트 · 가격 · 쿠폰 · 사은품'],['실행 연결','Cafe24 · 랜딩 · CRM'],['출시 검증','기간 · 옵션가 · 재고 · 물류']])+'<p class="flow-caption">프로모션 실행 범위를 정리한 개념도입니다.</p><p>페이지 카피에서 쿠폰과 금액별 사은품의 오해를 줄이고, 콘텐츠 블록과 JSON을 실제 페이지에 연결했습니다. 오픈 전에는 URL·중복·기간·옵션가·재고·물류를 확인했습니다.</p>'],
['results','기획부터 성과까지 같은 정보로 이어지게 했습니다.',table(['업무','시스템에서 연결한 흐름'],[['회차 기획','결정문과 선례를 바탕으로 기획안 생성'],['쿠폰 실행','자동 생성 후 재조회 검증'],['페이지 제작','페이지 JSON 내보내기와 에디터 불러오기'],['사전 QA','마진과 쿠폰 조건 검사'],['성과 분석','쿠폰명 태그로 캠페인 성과 그룹화']])+'<p>WBL과 VIVOIR 두 브랜드를 대상으로 20일 동안 22개 화면과 82개 API 경로를 구축했습니다. 기획안 기준 Railway 프로덕션에서 운영 중입니다.</p>'+source+'<p class="note">모든 이상을 작업 중단 조건으로 두면 예외가 많은 실무를 막을 수 있습니다. 되돌리기 어려운 외부 쓰기는 차단하고, 나머지는 기본값·자동 보정·경고로 처리하는 기준을 설계했습니다. 검증하지 못한 항목은 미검증 상태로 남깁니다.</p>'],
['limits','도입과 효과 측정은 구분합니다.','<p>현재 확인된 서술은 프로덕션 운영 상태입니다. 회차 세팅 시간, 오픈 후 수정 건수, 쿠폰 오설정 건수의 개선 폭은 실측 후 추가할 항목입니다.</p><p>사은품 배선, 겹치는 상품 대체 추천, 레거시 콘솔 퇴역은 다음 단계입니다. 완료 성과로 표현하지 않습니다.</p>']]},
{id:'workbench',category:'PPL · 업무 도구',name:'PPL Workbench 구축과 도입',summary:'크리에이터 검토부터 성과 회고까지, 흩어진 정보를 연결했습니다.',outcome:'마케팅팀 공식 도구 채택',foot:'현업 흐름을 제품으로',title:'흩어진 PPL 업무를<br>팀이 쓰는 하나의 흐름으로.',intro:'크리에이터 검토, 제안, 실행, 추적과 회고를 같은 정보 구조로 연결하는 업무 도구를 만들었습니다.',role:'업무 정의 · 웹앱 구현 · 운영 피드백 반영',scope:'Google Apps Script · Claude Code',sections:[
['problem','진행 상태보다 정보를 찾는 일이 먼저였습니다.','<p>크리에이터 검토, 단가, 일정, 메일, UTM, 랜딩과 성과 정보가 여러 시트와 대화방에 흩어져 있었습니다. 제안부터 발행과 ROAS 회고까지 같은 정보를 반복 입력했고, 누락 여부를 한눈에 보기 어려웠습니다.</p>'],
['decision','기능 목록보다 실무의 판단 순서를 먼저 정했습니다.',flow([['검토 · 제안','채널 적합도 · 조건 · 일정'],['실행','가이드 · 계약 · 배송 · QA'],['추적','랜딩 · 쿠폰 · UTM'],['회고','브랜드별 성과와 히스토리']])+'<p class="flow-caption">기획안에 제시된 업무 흐름을 재구성한 개념도입니다.</p><p>현업의 판단 단계와 필수 필드를 직접 정의했습니다. 크리에이터 비교와 검토 기록, 메일 템플릿과 제안 상태, 실행 체크리스트를 같은 흐름 안에 배치했습니다.</p><p>Claude Code와 Google Apps Script를 활용해 웹앱으로 구현하고 운영 피드백을 반영했습니다. 기능 수를 늘리기보다 실제 비브아 캠페인 한 사이클을 끝까지 운영할 수 있는 흐름을 우선했습니다.</p>'],
['results','마케팅팀의 공식 업무 도구로 채택됐습니다.','<p>크리에이터 검토부터 성과 회고까지 같은 정보 구조를 재사용할 수 있게 됐습니다. 기획안은 마케팅팀 공식 업무 도구 채택을 결과로 기록하고 있습니다.</p>'+source+'<p class="note">이 사례의 핵심 결과는 도구의 실제 채택입니다. 시간 절감률이나 매출 증가율은 측정 자료가 없어 제시하지 않습니다.</p>'],
['limits','완료 기능과 다음 단계를 나눕니다.','<p>모두싸인 API 계약 연동은 미완료 로드맵입니다. 실제 운영 화면과 도입 확인 자료를 보완하고, 반복 입력 감소와 누락 방지 효과는 별도로 측정할 계획입니다.</p>']]},
{id:'campaigns',category:'CRM · 행동 자동화',name:'행동 기반 CRM 자동화',summary:'구매 의도가 높은 순간에 맞춰 고객을 다시 연결했습니다.',outcome:'최대 ROAS 3,347%',foot:'주문서 이탈 시나리오',title:'구매 의도가 사라지기 전에,<br>행동 데이터로 다시 연결하다.',intro:'주문서 이탈, 쿠폰 만료, 신규 가입과 장바구니 행동을 각각의 전환 시나리오로 운영하고 성과를 비교했습니다.',role:'CRM 시나리오 운영 · 소재 제작 · 발송 · 성과 분석',scope:'Cafe24 · Datarize · SnapPush · Figma',basis:'2026년 8–9월 CRM 자료',sections:[
['problem','같은 CRM이라도, 고객 상태에 따라 성과가 달랐습니다.','<p>외부 파트너와의 운영 리뷰에서 고관심 고객군은 ROAS 2,209%, 신규 가입 미구매 고객군은 882%, 멤버십 안내는 941%, 기존 구매 고객군은 289%로 차이가 컸습니다. 캠페인을 많이 운영하는 것보다 고객이 현재 어떤 상태인지 먼저 구분해야 한다는 신호였습니다.</p>'+meetingSource+'<p>프로모션 일정 중심의 일괄 발송만으로는 고객이 구매를 망설이는 순간과 메시지를 연결하기 어려웠습니다. 발송량보다 어떤 행동을 한 고객에게 언제 다시 방문할 이유를 줄 것인지가 핵심 문제였습니다.</p>'],
['decision','고객 행동마다 다른 전환 이유를 연결했습니다.','<p>행동이 발생한 맥락에 맞춰 주문서 이탈, 쿠폰 만료, 신규 가입과 장바구니 시나리오를 구분했습니다. 각 고객군의 타깃 조건과 메시지의 핵심 혜택을 나누고, 클릭 이후에도 같은 상품과 혜택을 확인하도록 랜딩 흐름을 연결했습니다.</p>'+flow([['주문서 이탈','구매 직전 망설임 해소'],['쿠폰 만료','사용 기한과 혜택 환기'],['신규 가입','첫 구매 이유 제공'],['장바구니','관심 상품의 변화 알림']])+'<p class="flow-caption">운영한 행동 기반 CRM 시나리오를 재구성한 개념도입니다.</p><p>캠페인별 UTM을 적용해 CTR, 주문, 전환매출과 ROAS를 함께 추적했습니다. 높은 클릭률뿐 아니라 실제 매출로 이어졌는지를 기준으로 성과를 비교했습니다.</p>'],
['results','행동과 시점을 연결한 캠페인에서 높은 전환 효율을 확인했습니다.',table(['CRM 시나리오','CTR','전환매출','ROAS'],[['주문서 이탈','<strong>24.82%</strong>','65.6만 원','<strong>3,347%</strong>'],['쿠폰 만료 3일 전','17.04%','142.3만 원','<strong>3,336%</strong>'],['회원가입 감사쿠폰','18.56%','—','844%'],['장바구니 할인 상품','14.39%','—','507%']])+dashboardSource+'<p class="note">주문서 이탈 캠페인은 구매 5건을 기록했습니다. 전환매출이 확인되지 않은 시나리오는 대시로 표기했으며, 플랫폼별 귀속 기준이 다른 수치는 합산하지 않았습니다.</p>'],
['limits','높은 ROAS보다 반복 가능한 조건을 남깁니다.','<p>주문서 이탈 캠페인의 ROAS는 높았지만 구매 5건의 소규모 표본입니다. 단일 캠페인의 결과를 전체 고객에게 일반화하지 않고, 동일 조건에서 반복했을 때의 전환율과 매출 규모를 함께 확인해야 합니다.</p><p>미팅에서 확인한 다음 과제는 반복되는 이미지와 문구를 다변화하고, 신규 가입 고객의 미구매 기간과 장기 미방문 기간별로 메시지를 세분화하는 것입니다. 채널·일정·혜택·소재를 캘린더로 관리하되, 이는 제안 단계이므로 완료 성과로 표현하지 않습니다.</p>']]}
];
function flow(items){return '<div class="flow">'+items.map(([a,b])=>`<div><b>${a}</b><span>${b}</span></div>`).join('')+'</div>';}
function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>i?`<td>${x}</td>`:`<th scope="row">${x}</th>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function shell(title,body,depth=''){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="남귀현의 경력 포트폴리오. CRM과 프로모션 실행에서 반복 가능한 운영 시스템까지."><meta name="theme-color" content="#183b50"><title>${title} | 남귀현 포트폴리오</title><link rel="stylesheet" href="${depth}assets/style.css"><link rel="stylesheet" href="${depth}assets/impact.css"><script defer src="${depth}assets/app.js"></script></head><body><a class="skip" href="#main">본문으로 건너뛰기</a><div class="wrap"><header class="header"><a class="brand" href="${depth}index.html">남귀현<span>경력 포트폴리오</span></a><nav class="nav" aria-label="주 메뉴"><a href="${depth}index.html#projects">프로젝트</a><a href="${depth}index.html#about">소개</a></nav></header>${body}<footer class="footer"><span>남귀현 · CRM과 프로모션, 그리고 운영 시스템</span><span>2026년 9월 기준 · <button class="print" data-print>이 페이지 인쇄</button></span><a href="#main">맨 위로</a></footer></div></body></html>`;}
const home=`<main id="main"><section class="hero intro-fade"><div class="hero-top"><div class="switch" role="group" aria-label="포트폴리오 관점"><button data-view="marketing" aria-pressed="true">CRM·마케팅</button><button data-view="ops" aria-pressed="false">운영 시스템</button></div></div><h1 data-hero>고객의 다음 행동을 설계하고,<br><em>반복되는 일을 시스템으로.</em></h1><div class="hero-bottom"><p>안녕하세요, 이커머스 마케터 남귀현입니다.<br>고객 행동을 전환 시나리오로 설계하고, 효율과 매출 규모를 함께 읽어 다음 실행의 기준을 만듭니다.</p><a class="text-link" href="#projects">프로젝트 살펴보기 ${arrow}</a></div></section><section class="result-panel" aria-labelledby="result-title"><div><h2 id="result-title">고객 행동을,<br>전환 시나리오로 연결했습니다.</h2><p>담당 기간 CRM 성과 대시보드<br>규모와 효율을 함께 봅니다.</p></div><div class="impact-grid"><div><span>최대 ROAS</span><strong>3,347%</strong><small>주문서 이탈 시나리오</small></div><div><span>전환매출</span><strong>1,186만 원</strong><small>담당 기간 추적값</small></div><div><span>주문</span><strong>149건</strong><small>담당 기간 추적값</small></div></div></section>${dashboardSource}<section class="section" id="projects"><div class="section-head"><h2>실행에서 구조로</h2><p>발견부터 회고까지, 판단 과정이 보이는 네 가지 사례</p></div><div class="project-list">${projects.map(p=>`<a class="project" data-project="${p.id}" data-case-link href="projects/${p.id}.html"><span class="category">${p.category}</span><div class="summary"><h3>${p.name}</h3><p>${p.summary}</p></div><div class="outcome">${p.outcome}<small>${p.foot}</small></div>${arrow}</a>`).join('')}</div></section><section class="section about-grid" id="about"><h2>한 번의 실행이<br>다음의 기준이 되도록.</h2><div class="about-copy"><p>캠페인에서 발견한 문제를 데이터로 정의하고,<br>다음 운영에서 다시 쓸 수 있는 규칙으로 정리합니다.</p><div class="roles"><div><h3>고객 여정과 CRM</h3><p>신규·고관심·구매·장기 미방문을 나눠 유입부터 재활성화까지 연결합니다.</p></div><div><h3>프로모션 PM</h3><p>채널·일정·혜택·소재와 QA를 하나의 출시 흐름으로 다룹니다.</p></div><div><h3>업무 시스템</h3><p>실무의 판단과 필수 조건을 정의하고, 반복 입력과 검증을 도구로 옮깁니다.</p></div><div><h3>성과를 읽는 방식</h3><p>ROAS가 올라도 매출 규모가 줄면 성장으로 포장하지 않고, 효율과 규모를 분리해 봅니다.</p></div></div></div></section></main>`;
await mkdir('site/projects',{recursive:true});await writeFile('site/index.html',shell('CRM과 프로모션을 운영 시스템으로',home));
for(let i=0;i<projects.length;i++){const p=projects[i];const next=projects[(i+1)%projects.length];const body=`<main id="main"><div class="breadcrumb"><a href="../index.html#projects">프로젝트</a> / ${p.name}</div><header class="case-hero"><h1>${p.title}</h1><p class="lede">${p.intro}</p><dl class="meta"><div><dt>담당 범위</dt><dd>${p.role}</dd></div><div><dt>운영 환경</dt><dd>${p.scope}</dd></div><div><dt>자료 기준</dt><dd>${p.basis||'2026년 9월 기획안'}</dd></div></dl></header><div class="case-layout"><nav class="toc" aria-label="사례 목차"><a href="#problem">발견과 문제 정의</a><a href="#decision">가설·판단과 실행</a><a href="#results">결과</a><a href="#limits">회고와 다음 단계</a></nav><article>${p.sections.map(([id,title,html])=>`<section class="case-section" id="${id}"><h2>${title}</h2>${html}</section>`).join('')}</article></div><nav class="case-bottom" aria-label="다른 프로젝트"><a class="text-link" href="../index.html#projects">프로젝트 목록</a><a class="text-link" href="${next.id}.html">${next.name} ${arrow}</a></nav></main>`;await writeFile(`site/projects/${p.id}.html`,shell(p.name,body,'../'));}
await writeFile('site/.nojekyll','');
await writeFile('site/404.html',shell('페이지를 찾을 수 없습니다','<main id="main" class="hero"><h1>페이지를 찾을 수 없습니다.</h1><p class="lede">주소를 확인하거나 포트폴리오 홈으로 돌아가 주세요.</p><a class="text-link" href="./index.html">포트폴리오 홈</a></main>'));
const {readFile}=await import('node:fs/promises');
await writeFile('site/404.html',(await readFile('site/404.html','utf8')).replace('<head>','<head><base href="https://namgh98-star.github.io/nam-gwihyeon-portfolio/">'));
console.log('홈, 프로젝트 4개, 404 페이지 생성 완료');
